// ==========================================
// Nature Tours Plan Cart
// Destinations + tour plans + traveller details + day-wise planner
// ==========================================
"use strict";

const PLAN_CART_KEY = "natureToursPlanCart";
const PLAN_CART_WHATSAPP = "919822339466";
const PLAN_CART_TIMELINE_KEY = "natureToursTripTimeline";

function planCartRead(){try{const v=JSON.parse(localStorage.getItem(PLAN_CART_KEY)||"[]");return Array.isArray(v)?v:[]}catch(_){return[]}}
function planCartWrite(items){localStorage.setItem(PLAN_CART_KEY,JSON.stringify(items));document.dispatchEvent(new CustomEvent("natureToursPlanCartUpdated"))}
function timelineRead(){try{const v=JSON.parse(localStorage.getItem(PLAN_CART_TIMELINE_KEY)||"[]");return Array.isArray(v)?v:[]}catch(_){return[]}}
function timelineWrite(items){localStorage.setItem(PLAN_CART_TIMELINE_KEY,JSON.stringify(items));document.dispatchEvent(new CustomEvent("natureToursTripTimelineUpdated"))}
function planCartAdd(item){if(!item?.id||!item?.destination)return false;const items=planCartRead();if(items.some(x=>x.id===item.id))return false;items.push(item);planCartWrite(items);return true}
function planCartEscape(v=""){return String(v).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;").replace(/'/g,"&#039;")}
function planCartCount(){return planCartRead().length}
function destinationToCartItem(d){if(!d)return null;const id=String(d.id||d.name||"destination").trim().toLowerCase();return{id:`destination-${id}`,type:"destination",destination:d.name||d.destination||"Destination",country:d.country||"",duration:d.duration||"Custom plan",style:d.style||"Custom itinerary"}}
function itineraryToCartItem(p){return{id:`itinerary-${p.id}`,sourceId:p.id,type:"itinerary",destination:p.destination,country:p.country||"",duration:p.duration||"Custom plan",style:p.style||"Tour plan",image:p.image||"",days:Array.isArray(p.days)?p.days:[]}}
async function loadPlanDestinations(){let d=[];try{if(window.DestinationEngine)d=await window.DestinationEngine.load()}catch(_){}try{const x=JSON.parse(localStorage.getItem("natureToursDynamicDestination")||"null");if(x?.name&&!d.some(v=>String(v.id)===String(x.id)))d.push(x)}catch(_){}return Array.isArray(d)?d:[]}
async function ensureItineraryCatalogue(){if(Array.isArray(window.INTERNATIONAL_ITINERARIES))return;await new Promise(resolve=>{const s=document.createElement("script");s.src="js/itineraries.js?v=5";s.onload=resolve;s.onerror=resolve;document.head.appendChild(s)})}
function ensurePlanCartStyles(){if(document.querySelector('link[data-nature-plan-cart-css]'))return;const l=document.createElement("link");l.rel="stylesheet";l.href="css/plan-cart.css?v=7";l.dataset.naturePlanCartCss="true";document.head.appendChild(l)}

function ensurePlanCartMarkup(){
 if(document.getElementById("plan-cart-panel"))return;
 const b=document.createElement("button");b.id="open-plan-cart";b.className="plan-cart-open-btn";b.type="button";b.innerHTML='🧳 My Plan Cart <span class="plan-cart-badge" data-plan-cart-count hidden>0</span>';document.body.appendChild(b);
 const p=document.createElement("div");p.id="plan-cart-panel";p.className="plan-cart-panel";p.setAttribute("aria-hidden","true");
 p.innerHTML=`<div id="plan-cart-backdrop" class="plan-cart-backdrop"></div><aside class="plan-cart-drawer" aria-label="My travel plan cart">
 <div class="plan-cart-head"><div><span class="sub-badge">Build Your Trip</span><h2>My Plan Cart</h2><p class="plan-cart-subtitle">Choose destinations, tour plans and build your trip day by day.</p></div><button id="close-plan-cart" class="plan-cart-close" type="button" aria-label="Close">×</button></div>
 <div class="plan-cart-tabs"><button type="button" class="plan-cart-tab is-active" data-plan-tab="destinations">📍 Destinations</button><button type="button" class="plan-cart-tab" data-plan-tab="plans">🗺️ Tour Plans</button></div>
 <div id="plan-cart-destination-picker" class="plan-destination-picker"><label for="plan-destination-search">Search destinations</label><div class="plan-destination-search-wrap"><span class="plan-destination-search-icon">⌕</span><input id="plan-destination-search" type="search" autocomplete="off" placeholder="Search Paris, Bali, Ladakh..." aria-label="Search destinations"></div><div id="plan-destination-results" class="plan-destination-results"></div></div>
 <div id="plan-cart-plan-picker" class="plan-destination-picker" hidden><label for="plan-plan-search">Search tour plans</label><div class="plan-destination-search-wrap"><span class="plan-destination-search-icon">⌕</span><input id="plan-plan-search" type="search" autocomplete="off" placeholder="Search Paris Classic, Bali Escape..." aria-label="Search tour plans"></div><div id="plan-plan-results" class="plan-destination-results"></div></div>
 <div class="plan-cart-section-title"><span>Selected for your trip</span><strong data-plan-cart-count>0</strong></div><div id="plan-cart-empty" class="plan-cart-empty">Nothing selected yet. Add a destination or tour plan above.</div><div id="plan-cart-list"></div>
 <section class="trip-planner-section"><div class="trip-planner-heading"><div><span class="trip-planner-kicker">🗓️ Build your route</span><h3>Day-wise Trip Planner</h3><p>Arrange your stops and choose how many days you want at each one.</p></div><strong id="trip-planner-total-days">0 days</strong></div><div id="trip-planner-list" class="trip-planner-list"></div><div id="trip-planner-empty" class="trip-planner-empty">Add destinations or tour plans above to start your day-wise itinerary.</div></section>
 <form id="plan-cart-enquiry-form" class="plan-cart-form">
  <div class="plan-cart-form-title">👥 Number of Travellers</div><p class="plan-cart-form-help">Tick only the traveller types that apply to your trip, then enter the number for each selected type.</p>
  <div class="traveller-option"><label class="traveller-check"><input type="checkbox" id="traveller-adults-enabled" name="adultsEnabled"><span>No. of adults</span></label><input class="traveller-number" id="traveller-adults" name="adults" type="number" min="1" max="99" value="1" disabled></div>
  <div class="traveller-option"><label class="traveller-check"><input type="checkbox" id="traveller-kids-enabled" name="kidsEnabled"><span>No. of kids <small>(age 4 to 18)</small></span></label><input class="traveller-number" id="traveller-kids" name="kids" type="number" min="1" max="99" value="1" disabled></div>
  <div class="traveller-option"><label class="traveller-check"><input type="checkbox" id="traveller-babies-enabled" name="babiesEnabled"><span>No. of babies <small>(age 0 to 4)</small></span></label><input class="traveller-number" id="traveller-babies" name="babies" type="number" min="1" max="99" value="1" disabled></div>
  <div class="traveller-option"><label class="traveller-check"><input type="checkbox" id="traveller-seniors-enabled" name="seniorsEnabled"><span>No. of senior citizens <small>(60 and above)</small></span></label><input class="traveller-number" id="traveller-seniors" name="seniors" type="number" min="1" max="99" value="1" disabled></div>
  <div class="traveller-option traveller-special-option"><label class="traveller-check"><input type="checkbox" id="traveller-special-enabled" name="specialEnabled"><span>Special passenger</span></label><div class="special-passenger-fields"><label for="traveller-special-description">Description of passenger</label><input id="traveller-special-description" name="specialDescription" type="text" placeholder="e.g. wheelchair user, medical assistance, infant equipment" disabled></div></div>
  <div class="traveller-total" id="traveller-total">Total travellers selected: 0</div>
  <div><label for="plan-cart-dates">Travel dates</label><input id="plan-cart-dates" name="travelDates" type="text" placeholder="e.g. 12–18 December 2026"></div>
  <div><label for="plan-cart-budget">Budget</label><input id="plan-cart-budget" name="budget" type="text" placeholder="e.g. ₹2–3 lakh"></div>
  <div><label for="plan-cart-notes">Other special requirements</label><textarea id="plan-cart-notes" name="notes" rows="3" placeholder="Hotel preference, flights, food, accessibility, honeymoon, etc."></textarea></div>
  <section class="trip-summary"><div class="trip-summary-title"><span>📋 Trip Summary</span><span class="trip-summary-live">LIVE</span></div><div id="trip-summary-content"></div></section>
  <button class="plan-cart-submit" type="submit">Send Complete Enquiry on WhatsApp</button><p class="plan-cart-note">No online payment or automatic booking. This is an enquiry basket.</p>
 </form></aside>`;document.body.appendChild(p);
}

let planDestinationCatalogue=[];
function updatePlanCartButtons(){const c=planCartCount();document.querySelectorAll("[data-plan-cart-count]").forEach(e=>{e.textContent=String(c);if(e.classList.contains("plan-cart-badge"))e.hidden=c===0})}
function parseDurationDays(v=""){const m=String(v).match(/(\d+)\s*Days?/i);return m?Math.max(1,Number(m[1])):1}
function syncTimelineWithCart(){const cart=planCartRead(),ids=new Set(cart.map(x=>x.id)),timeline=timelineRead().filter(x=>ids.has(x.itemId));cart.forEach(item=>{if(!timeline.some(x=>x.itemId===item.id))timeline.push({itemId:item.id,days:item.type==="itinerary"?(item.days?.length||parseDurationDays(item.duration)):1})});timelineWrite(timeline)}
function renderPlanCart(){const list=document.getElementById("plan-cart-list"),empty=document.getElementById("plan-cart-empty");if(!list||!empty)return;const items=planCartRead();empty.hidden=items.length>0;list.innerHTML=items.map(i=>`<article class="plan-cart-item"><div class="plan-cart-item-info"><span class="plan-cart-pin">${i.type==="itinerary"?"🗺️":"📍"}</span><div><h3>${planCartEscape(i.destination)}${i.country?`, ${planCartEscape(i.country)}`:""}</h3><p>${planCartEscape(i.duration||"Custom plan")} · ${planCartEscape(i.style||"Custom itinerary")}</p></div></div><button type="button" class="plan-cart-remove" data-remove-plan="${planCartEscape(i.id)}">Remove</button></article>`).join("");list.querySelectorAll("[data-remove-plan]").forEach(b=>b.onclick=()=>{const id=b.dataset.removePlan;planCartWrite(planCartRead().filter(x=>x.id!==id));timelineWrite(timelineRead().filter(x=>x.itemId!==id));renderAllCartUI()});updatePlanCartButtons()}
function renderTripPlanner(){const box=document.getElementById("trip-planner-list"),empty=document.getElementById("trip-planner-empty"),total=document.getElementById("trip-planner-total-days");if(!box||!empty)return;syncTimelineWithCart();const cart=planCartRead(),timeline=timelineRead(),byId=new Map(cart.map(x=>[x.id,x]));let day=1,totalDays=0;box.innerHTML=timeline.map((row,index)=>{const item=byId.get(row.itemId);if(!item)return"";const days=Math.max(1,Math.min(60,Number(row.days)||1)),start=day,end=day+days-1;day=end+1;totalDays+=days;return`<article class="trip-stop"><div class="trip-stop-order"><button type="button" data-move-stop="up" data-stop-index="${index}" aria-label="Move up">▲</button><span>${index+1}</span><button type="button" data-move-stop="down" data-stop-index="${index}" aria-label="Move down">▼</button></div><div class="trip-stop-main"><div class="trip-stop-top"><div><span class="trip-stop-days">Day ${start}${days>1?`–${end}`:""}</span><h4>${item.type==="itinerary"?"🗺️":"📍"} ${planCartEscape(item.destination)}</h4><p>${planCartEscape(item.country||"")} · ${planCartEscape(item.style||"Custom itinerary")}</p></div><button type="button" class="trip-stop-remove" data-stop-remove="${planCartEscape(item.id)}">×</button></div><div class="trip-stop-controls"><button type="button" data-days-action="minus" data-stop-id="${planCartEscape(item.id)}">−</button><strong>${days} ${days===1?"day":"days"}</strong><button type="button" data-days-action="plus" data-stop-id="${planCartEscape(item.id)}">+</button></div></div></article>`}).join("");empty.hidden=timeline.length>0;if(total)total.textContent=`${totalDays} ${totalDays===1?"day":"days"}`;bindPlannerEvents()}
function bindPlannerEvents(){document.querySelectorAll("[data-days-action]").forEach(b=>b.onclick=()=>{const t=timelineRead(),r=t.find(x=>x.itemId===b.dataset.stopId);if(!r)return;r.days=Math.max(1,Math.min(60,(Number(r.days)||1)+(b.dataset.daysAction==="plus"?1:-1)));timelineWrite(t);renderTripPlanner();renderTripSummary()});document.querySelectorAll("[data-stop-remove]").forEach(b=>b.onclick=()=>{const id=b.dataset.stopRemove;planCartWrite(planCartRead().filter(x=>x.id!==id));timelineWrite(timelineRead().filter(x=>x.itemId!==id));renderAllCartUI()});document.querySelectorAll("[data-move-stop]").forEach(b=>b.onclick=()=>{const t=timelineRead(),i=Number(b.dataset.stopIndex),j=b.dataset.moveStop==="up"?i-1:i+1;if(j<0||j>=t.length)return;[t[i],t[j]]=[t[j],t[i]];timelineWrite(t);renderTripPlanner();renderTripSummary()})}
function renderDestinationResults(){const box=document.getElementById("plan-destination-results");if(!box)return;const q=(document.getElementById("plan-destination-search")?.value||"").trim().toLowerCase(),selected=new Set(planCartRead().map(x=>x.id));const m=planDestinationCatalogue.filter(d=>[d.name,d.country,d.continent,d.region,d.state,...(d.tags||[])].filter(Boolean).join(" ").toLowerCase().includes(q)).slice(0,q?15:10);box.innerHTML=m.length?m.map(d=>{const i=destinationToCartItem(d),a=selected.has(i.id);return`<button type="button" class="plan-destination-result ${a?"is-added":""}" data-pick-destination="${planCartEscape(d.id||d.name)}"><span class="plan-destination-result-icon">${d.type==="domestic"||d.country==="India"?"🇮🇳":"🌍"}</span><span class="plan-destination-result-text"><strong>${planCartEscape(d.name)}</strong><small>${planCartEscape(d.country||"")} · ${planCartEscape(d.region||d.state||d.continent||"")}</small></span><span class="plan-destination-result-action">${a?"✓ Added":"+ Add"}</span></button>`}).join(""):"<div class=\"plan-destination-no-results\">No destination found. Try another spelling.</div>";box.querySelectorAll("[data-pick-destination]").forEach(b=>b.onclick=()=>{const d=planDestinationCatalogue.find(x=>String(x.id||x.name)===String(b.dataset.pickDestination));if(d)planCartAdd(destinationToCartItem(d));renderAllCartUI()})}
function renderPlanResults(){const box=document.getElementById("plan-plan-results");if(!box)return;const q=(document.getElementById("plan-plan-search")?.value||"").trim().toLowerCase(),plans=Array.isArray(window.INTERNATIONAL_ITINERARIES)?window.INTERNATIONAL_ITINERARIES:[],selected=new Set(planCartRead().map(x=>x.id));const m=plans.filter(p=>[p.destination,p.country,p.style,p.duration,...(p.highlights||[])].join(" ").toLowerCase().includes(q));box.innerHTML=m.length?m.map(p=>{const i=itineraryToCartItem(p),a=selected.has(i.id);return`<button type="button" class="plan-destination-result ${a?"is-added":""}" data-pick-plan="${planCartEscape(p.id)}"><span class="plan-destination-result-icon">🗺️</span><span class="plan-destination-result-text"><strong>${planCartEscape(p.destination)} — ${planCartEscape(p.style)}</strong><small>${planCartEscape(p.duration)} · ${planCartEscape((p.highlights||[]).slice(0,3).join(" · "))}</small></span><span class="plan-destination-result-action">${a?"✓ Added":"+ Add"}</span></button>`}).join(""):"<div class=\"plan-destination-no-results\">No tour plan found.</div>";box.querySelectorAll("[data-pick-plan]").forEach(b=>b.onclick=()=>{const p=plans.find(x=>x.id===b.dataset.pickPlan);if(p)planCartAdd(itineraryToCartItem(p));renderAllCartUI()})}
function switchPlanTab(tab){document.querySelectorAll(".plan-cart-tab").forEach(b=>b.classList.toggle("is-active",b.dataset.planTab===tab));const d=document.getElementById("plan-cart-destination-picker"),p=document.getElementById("plan-cart-plan-picker");if(d)d.hidden=tab!=="destinations";if(p)p.hidden=tab!=="plans";if(tab==="plans")renderPlanResults();else renderDestinationResults()}
function travellerSummary(form){const get=(enabled,id)=>form.querySelector(enabled)?.checked?Number(form.querySelector(id)?.value||0):0;const adults=get("#traveller-adults-enabled","#traveller-adults"),kids=get("#traveller-kids-enabled","#traveller-kids"),babies=get("#traveller-babies-enabled","#traveller-babies"),seniors=get("#traveller-seniors-enabled","#traveller-seniors"),special=form.querySelector("#traveller-special-enabled")?.checked?(form.querySelector("#traveller-special-description")?.value.trim()||"Special assistance requested"):"";return{adults,kids,babies,seniors,special,total:adults+kids+babies+seniors}}
function updateTravellerUI(form){const pairs=[["#traveller-adults-enabled","#traveller-adults"],["#traveller-kids-enabled","#traveller-kids"],["#traveller-babies-enabled","#traveller-babies"],["#traveller-seniors-enabled","#traveller-seniors"],["#traveller-special-enabled","#traveller-special-description"]];pairs.forEach(([c,i])=>{const enabled=form.querySelector(c)?.checked,field=form.querySelector(i);if(field)field.disabled=!enabled});const s=travellerSummary(form),el=form.querySelector("#traveller-total");if(el)el.textContent=`Total travellers selected: ${s.total}`;renderTripSummary()}
function renderTripSummary(){const box=document.getElementById("trip-summary-content"),form=document.getElementById("plan-cart-enquiry-form");if(!box||!form)return;const cart=planCartRead(),t=timelineRead(),byId=new Map(cart.map(x=>[x.id,x])),s=travellerSummary(form),dates=form.querySelector("#plan-cart-dates")?.value.trim()||"Not specified",budget=form.querySelector("#plan-cart-budget")?.value.trim()||"Not specified",stops=t.map(x=>byId.get(x.itemId)).filter(Boolean),totalDays=t.reduce((n,x)=>n+Math.max(1,Number(x.days)||1),0);box.innerHTML=`<div class="trip-summary-grid"><div><span>📍 Destinations</span><strong>${cart.filter(x=>x.type==="destination").length}</strong></div><div><span>🗺️ Tour plans</span><strong>${cart.filter(x=>x.type==="itinerary").length}</strong></div><div><span>🗓️ Trip length</span><strong>${totalDays} ${totalDays===1?"day":"days"}</strong></div><div><span>👥 Travellers</span><strong>${s.total}</strong></div></div><div class="trip-summary-lines"><p><b>Route:</b> ${stops.length?stops.map(x=>planCartEscape(x.destination)).join(" → "):"Not planned yet"}</p><p><b>Dates:</b> ${planCartEscape(dates)}</p><p><b>Budget:</b> ${planCartEscape(budget)}</p>${s.special?`<p><b>Special passenger:</b> ${planCartEscape(s.special)}</p>`:""}</div>`}
function buildWhatsAppLink(items,form){const s=travellerSummary(form),t=timelineRead(),byId=new Map(items.map(x=>[x.id,x]));let day=1;const route=t.map(x=>{const item=byId.get(x.itemId);if(!item)return"";const n=Math.max(1,Number(x.days)||1),start=day,end=day+n-1;day=end+1;return`• Day ${start}${n>1?`–${end}`:""}: ${item.destination}${item.country?`, ${item.country}`:""} — ${item.style||"Custom plan"}`}).filter(Boolean).join("%0A");const dates=encodeURIComponent(form.travelDates.value.trim()||"Not specified"),budget=encodeURIComponent(form.budget.value.trim()||"Not specified"),notes=encodeURIComponent(form.notes.value.trim()||"None"),special=encodeURIComponent(s.special||"None");const travellers=`Adults: ${s.adults}%0AKids (4–18): ${s.kids}%0ABabies (0–4): ${s.babies}%0ASenior citizens (60+): ${s.seniors}%0ASpecial passenger: ${special}%0ATotal: ${s.total}`;const message=`Hello Nature Tours,%0A%0AI would like to discuss this trip:%0A%0A*Day-wise itinerary*%0A${route||"• No route selected"}%0A%0A*Travellers*%0A${travellers}%0A%0ATravel dates: ${dates}%0ABudget: ${budget}%0ASpecial requirements: ${notes}%0A%0APlease contact me with a customised plan and quotation.%0A%0AThank you.`;return`https://wa.me/${PLAN_CART_WHATSAPP}?text=${message}`}
function renderAllCartUI(){renderPlanCart();renderTripPlanner();renderTripSummary();updateTravellerUI(document.getElementById("plan-cart-enquiry-form")||document.createElement("form"));updatePlanCartButtons();renderDestinationResults();renderPlanResults()}
function openPlanCart(){const panel=document.getElementById("plan-cart-panel");if(!panel)return;panel.classList.add("is-open");panel.setAttribute("aria-hidden","false");Promise.all([ensureItineraryCatalogue(),loadPlanDestinations()]).then(([,d])=>{planDestinationCatalogue=d;renderAllCartUI()})}
function closePlanCart(){const panel=document.getElementById("plan-cart-panel");if(panel){panel.classList.remove("is-open");panel.setAttribute("aria-hidden","true")}}
function ensureCardButtonStyles(){if(document.getElementById("nature-plan-card-button-style"))return;const s=document.createElement("style");s.id="nature-plan-card-button-style";s.textContent=`.nature-plan-card-action{margin-top:12px;width:100%;border:0;border-radius:9px;padding:9px 12px;background:#168bd3;color:#fff;font-weight:800;font-size:12px;cursor:pointer}.nature-plan-card-action.is-added{background:#0f9d58}.nature-current-destination-action{margin:18px 0 6px!important;display:inline-flex!important;width:auto!important}`;document.head.appendChild(s)}
function cardPlanData(card){const h=card.querySelector("h3,h4,h2"),img=card.querySelector("img");if(!h||!img)return null;const n=h.textContent.trim();if(!n||/nature tours|wild safaris|honeymoon packages|medical tourism|sample international itineraries/i.test(n))return null;const found=planDestinationCatalogue.find(d=>d.name&&n.toLowerCase().includes(String(d.name).toLowerCase()));return found?destinationToCartItem(found):{id:`card-${location.pathname}-${n.toLowerCase().replace(/[^a-z0-9]+/g,"-")}`,type:"destination",destination:n,country:"",duration:"Custom plan",style:"Custom itinerary"}}
function enhancePlanCards(){ensureCardButtonStyles();document.querySelectorAll(".glance-card,.destination-card,.search-result-card,.result-card").forEach(card=>{if(card.querySelector(".nature-plan-card-action")||card.querySelector(".itinerary-secondary"))return;const item=cardPlanData(card);if(!item)return;const b=document.createElement("button");b.type="button";b.className="nature-plan-card-action";const sync=()=>{const a=planCartRead().some(x=>x.id===item.id);b.textContent=a?"✓ Added to Plan":"🧳 Add to Plan";b.classList.toggle("is-added",a)};sync();b.onclick=()=>{planCartAdd(item);sync();openPlanCart()};(card.querySelector(".card-meta")||card).appendChild(b)})}
async function addCurrentDestinationButton(){const host=document.getElementById("destination-page");if(!host)return;const run=async()=>{if(host.querySelector(".nature-current-destination-action"))return;let d=null;try{const id=new URLSearchParams(location.search).get("id");if(window.DestinationEngine){const all=await window.DestinationEngine.load();d=all.find(x=>String(x.id)===String(id))}if(!d)d=JSON.parse(localStorage.getItem("natureToursDynamicDestination")||"null")}catch(_){}if(!d)return;const i=destinationToCartItem(d),b=document.createElement("button");b.type="button";b.className="nature-plan-card-action nature-current-destination-action";const sync=()=>{const a=planCartRead().some(x=>x.id===i.id);b.textContent=a?"✓ Added to My Plan":"🧳 Add to My Plan";b.classList.toggle("is-added",a)};sync();b.onclick=()=>{planCartAdd(i);sync();openPlanCart()};const h=host.querySelector("h1,h2,h3");(h?.parentElement||host).appendChild(b)};run();let tries=0;const timer=setInterval(()=>{tries++;run();if(tries>40)clearInterval(timer)},250)}
function bindForm(){const form=document.getElementById("plan-cart-enquiry-form");if(!form||form.dataset.bound)return;form.dataset.bound="true";form.addEventListener("input",()=>{updateTravellerUI(form);renderTripSummary()});form.querySelectorAll("input[type=checkbox]").forEach(c=>c.addEventListener("change",()=>updateTravellerUI(form)));form.addEventListener("submit",e=>{e.preventDefault();const items=planCartRead(),s=travellerSummary(form);if(!items.length){alert("Please add at least one destination or tour plan first.");return}if(s.total<1){alert("Please select at least one traveller type and enter the number of travellers.");return}window.open(buildWhatsAppLink(items,form),"_blank","noopener,noreferrer")})}
function initializePlanCart(){ensurePlanCartStyles();ensurePlanCartMarkup();bindForm();const open=document.getElementById("open-plan-cart"),close=document.getElementById("close-plan-cart"),back=document.getElementById("plan-cart-backdrop");if(open&&!open.dataset.bound){open.onclick=openPlanCart;open.dataset.bound="true"}if(close&&!close.dataset.bound){close.onclick=closePlanCart;close.dataset.bound="true"}if(back&&!back.dataset.bound){back.onclick=closePlanCart;back.dataset.bound="true"}document.querySelectorAll("[data-plan-tab]").forEach(b=>b.onclick=()=>switchPlanTab(b.dataset.planTab));document.getElementById("plan-destination-search")?.addEventListener("input",renderDestinationResults);document.getElementById("plan-plan-search")?.addEventListener("input",renderPlanResults);document.addEventListener("keydown",e=>{if(e.key==="Escape")closePlanCart()});document.addEventListener("natureToursPlanCartUpdated",()=>{syncTimelineWithCart();renderAllCartUI();enhancePlanCards()});document.addEventListener("natureToursTripTimelineUpdated",()=>{renderTripPlanner();renderTripSummary()});window.addEventListener("storage",e=>{if(e.key===PLAN_CART_KEY||e.key===PLAN_CART_TIMELINE_KEY)renderAllCartUI()});const observer=new MutationObserver(()=>enhancePlanCards());observer.observe(document.body,{childList:true,subtree:true});loadPlanDestinations().then(d=>{planDestinationCatalogue=d;enhancePlanCards();renderDestinationResults()});ensureItineraryCatalogue().then(()=>renderPlanResults());addCurrentDestinationButton();updatePlanCartButtons();renderAllCartUI()}
window.NatureToursPlanCart={read:planCartRead,write:planCartWrite,add:planCartAdd,count:planCartCount,open:openPlanCart,close:closePlanCart,render:renderAllCartUI,timeline:timelineRead};
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",initializePlanCart,{once:true});else initializePlanCart();
