// ==========================================
// Nature Tours Plan Cart
// Destinations + tour plans + traveller details
// ==========================================
"use strict";

const PLAN_CART_KEY = "natureToursPlanCart";
const PLAN_CART_WHATSAPP = "919822339466";

function planCartRead(){try{const v=JSON.parse(localStorage.getItem(PLAN_CART_KEY)||"[]");return Array.isArray(v)?v:[]}catch(_){return[]}}
function planCartWrite(items){localStorage.setItem(PLAN_CART_KEY,JSON.stringify(items));document.dispatchEvent(new CustomEvent("natureToursPlanCartUpdated"))}
function planCartAdd(item){if(!item?.id||!item?.destination)return false;const items=planCartRead();if(items.some(x=>x.id===item.id))return false;items.push(item);planCartWrite(items);return true}
function planCartEscape(v=""){return String(v).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;").replace(/'/g,"&#039;")}
function planCartCount(){return planCartRead().length}
function destinationToCartItem(d){if(!d)return null;const id=String(d.id||d.name||"destination").trim().toLowerCase();return{id:`destination-${id}`,type:"destination",destination:d.name||d.destination||"Destination",country:d.country||"",duration:d.duration||"Custom plan",style:d.style||"Custom itinerary"}}
function itineraryToCartItem(p){return{id:`itinerary-${p.id}`,type:"itinerary",destination:p.destination,country:p.country||"",duration:p.duration||"Custom plan",style:p.style||"Tour plan",image:p.image||""}}
async function loadPlanDestinations(){let d=[];try{if(window.DestinationEngine)d=await window.DestinationEngine.load()}catch(_){}try{const x=JSON.parse(localStorage.getItem("natureToursDynamicDestination")||"null");if(x?.name&&!d.some(v=>String(v.id)===String(x.id)))d.push(x)}catch(_){}return Array.isArray(d)?d:[]}
async function ensureItineraryCatalogue(){if(Array.isArray(window.INTERNATIONAL_ITINERARIES))return;await new Promise(resolve=>{const s=document.createElement("script");s.src="js/itineraries.js?v=4";s.onload=resolve;s.onerror=resolve;document.head.appendChild(s)})}
function ensurePlanCartStyles(){if(document.querySelector('link[data-nature-plan-cart-css]'))return;const l=document.createElement("link");l.rel="stylesheet";l.href="css/plan-cart.css?v=6";l.dataset.naturePlanCartCss="true";document.head.appendChild(l)}

function ensurePlanCartMarkup(){
 if(document.getElementById("plan-cart-panel"))return;
 const b=document.createElement("button");b.id="open-plan-cart";b.className="plan-cart-open-btn";b.type="button";b.innerHTML='🧳 My Plan Cart <span class="plan-cart-badge" data-plan-cart-count hidden>0</span>';document.body.appendChild(b);
 const p=document.createElement("div");p.id="plan-cart-panel";p.className="plan-cart-panel";p.setAttribute("aria-hidden","true");
 p.innerHTML=`<div id="plan-cart-backdrop" class="plan-cart-backdrop"></div><aside class="plan-cart-drawer" aria-label="My travel plan cart">
 <div class="plan-cart-head"><div><span class="sub-badge">Build Your Trip</span><h2>My Plan Cart</h2><p class="plan-cart-subtitle">Choose destinations, tour plans and tell us exactly who is travelling.</p></div><button id="close-plan-cart" class="plan-cart-close" type="button" aria-label="Close">×</button></div>
 <div class="plan-cart-tabs"><button type="button" class="plan-cart-tab is-active" data-plan-tab="destinations">📍 Destinations</button><button type="button" class="plan-cart-tab" data-plan-tab="plans">🗺️ Tour Plans</button></div>
 <div id="plan-cart-destination-picker" class="plan-destination-picker"><label for="plan-destination-search">Search destinations</label><div class="plan-destination-search-wrap"><span class="plan-destination-search-icon">⌕</span><input id="plan-destination-search" type="search" autocomplete="off" placeholder="Search Paris, Bali, Ladakh..." aria-label="Search destinations"></div><div id="plan-destination-results" class="plan-destination-results"></div></div>
 <div id="plan-cart-plan-picker" class="plan-destination-picker" hidden><label for="plan-plan-search">Search tour plans</label><div class="plan-destination-search-wrap"><span class="plan-destination-search-icon">⌕</span><input id="plan-plan-search" type="search" autocomplete="off" placeholder="Search Paris Classic, Bali Escape..." aria-label="Search tour plans"></div><div id="plan-plan-results" class="plan-destination-results"></div></div>
 <div class="plan-cart-section-title"><span>Selected for your trip</span><strong data-plan-cart-count>0</strong></div><div id="plan-cart-empty" class="plan-cart-empty">Nothing selected yet. Add a destination or tour plan above, or use <b>Add to Plan</b> on the site.</div><div id="plan-cart-list"></div>
 <form id="plan-cart-enquiry-form" class="plan-cart-form">
  <div class="plan-cart-form-title">👥 Number of Travellers</div>
  <p class="plan-cart-form-help">Tick only the traveller types that apply to your trip, then enter the number for each selected type.</p>
  <div class="traveller-option"><label class="traveller-check"><input type="checkbox" id="traveller-adults-enabled" name="adultsEnabled"><span>No. of adults</span></label><input class="traveller-number" id="traveller-adults" name="adults" type="number" min="1" max="99" value="1" disabled></div>
  <div class="traveller-option"><label class="traveller-check"><input type="checkbox" id="traveller-kids-enabled" name="kidsEnabled"><span>No. of kids <small>(age 4 to 18)</small></span></label><input class="traveller-number" id="traveller-kids" name="kids" type="number" min="1" max="99" value="1" disabled></div>
  <div class="traveller-option"><label class="traveller-check"><input type="checkbox" id="traveller-babies-enabled" name="babiesEnabled"><span>No. of babies <small>(age 0 to 4)</small></span></label><input class="traveller-number" id="traveller-babies" name="babies" type="number" min="1" max="99" value="1" disabled></div>
  <div class="traveller-option"><label class="traveller-check"><input type="checkbox" id="traveller-seniors-enabled" name="seniorsEnabled"><span>No. of senior citizens <small>(60 and above)</small></span></label><input class="traveller-number" id="traveller-seniors" name="seniors" type="number" min="1" max="99" value="1" disabled></div>
  <div class="traveller-option traveller-special-option"><label class="traveller-check"><input type="checkbox" id="traveller-special-enabled" name="specialEnabled"><span>Special passenger</span></label><div class="special-passenger-fields"><label for="traveller-special-description">Description of passenger</label><input id="traveller-special-description" name="specialDescription" type="text" placeholder="e.g. wheelchair user, medical assistance, infant equipment" disabled></div></div>
  <div class="traveller-total" id="traveller-total">Total travellers selected: 0</div>
  <div><label for="plan-cart-dates">Travel dates</label><input id="plan-cart-dates" name="travelDates" type="text" placeholder="e.g. 12–18 December 2026"></div>
  <div><label for="plan-cart-budget">Budget</label><input id="plan-cart-budget" name="budget" type="text" placeholder="e.g. ₹2–3 lakh"></div>
  <div><label for="plan-cart-notes">Other special requirements</label><textarea id="plan-cart-notes" name="notes" rows="3" placeholder="Hotel preference, flights, food, accessibility, honeymoon, etc."></textarea></div>
  <button class="plan-cart-submit" type="submit">Send Complete Enquiry on WhatsApp</button><p class="plan-cart-note">No online payment or automatic booking. This is an enquiry basket.</p>
 </form></aside>`;document.body.appendChild(p);
}

let planDestinationCatalogue=[];
function updatePlanCartButtons(){const c=planCartCount();document.querySelectorAll("[data-plan-cart-count]").forEach(e=>{e.textContent=String(c);if(e.classList.contains("plan-cart-badge"))e.hidden=c===0})}
function renderPlanCart(){const list=document.getElementById("plan-cart-list"),empty=document.getElementById("plan-cart-empty");if(!list||!empty)return;const items=planCartRead();empty.hidden=items.length>0;list.innerHTML=items.map(i=>`<article class="plan-cart-item"><div class="plan-cart-item-info"><span class="plan-cart-pin">${i.type==="itinerary"?"🗺️":"📍"}</span><div><h3>${planCartEscape(i.destination)}${i.country?`, ${planCartEscape(i.country)}`:""}</h3><p>${planCartEscape(i.duration||"Custom plan")} · ${planCartEscape(i.style||"Custom itinerary")}</p></div></div><button type="button" class="plan-cart-remove" data-remove-plan="${planCartEscape(i.id)}">Remove</button></article>`).join("");list.querySelectorAll("[data-remove-plan]").forEach(b=>b.addEventListener("click",()=>{planCartWrite(planCartRead().filter(x=>x.id!==b.dataset.removePlan));renderPlanCart();renderDestinationResults();renderPlanResults()}));updatePlanCartButtons()}
function renderDestinationResults(){const box=document.getElementById("plan-destination-results");if(!box)return;const q=(document.getElementById("plan-destination-search")?.value||"").trim().toLowerCase(),selected=new Set(planCartRead().map(x=>x.id));const m=planDestinationCatalogue.filter(d=>[d.name,d.country,d.continent,d.region,...(d.tags||[])].filter(Boolean).join(" ").toLowerCase().includes(q)).slice(0,q?15:10);box.innerHTML=m.length?m.map(d=>{const i=destinationToCartItem(d),a=selected.has(i.id);return`<button type="button" class="plan-destination-result ${a?"is-added":""}" data-pick-destination="${planCartEscape(d.id||d.name)}"><span class="plan-destination-result-icon">${d.type==="domestic"?"🇮🇳":"🌍"}</span><span class="plan-destination-result-text"><strong>${planCartEscape(d.name)}</strong><small>${planCartEscape(d.country||"")} · ${planCartEscape(d.region||d.continent||"")}</small></span><span class="plan-destination-result-action">${a?"✓ Added":"+ Add"}</span></button>`}).join(""):"<div class=\"plan-destination-no-results\">No destination found. Try another spelling.</div>";box.querySelectorAll("[data-pick-destination]").forEach(b=>b.addEventListener("click",()=>{const d=planDestinationCatalogue.find(x=>String(x.id||x.name)===String(b.dataset.pickDestination));if(d)planCartAdd(destinationToCartItem(d));renderPlanCart();renderDestinationResults()}))}
function renderPlanResults(){const box=document.getElementById("plan-plan-results");if(!box)return;const q=(document.getElementById("plan-plan-search")?.value||"").trim().toLowerCase(),plans=Array.isArray(window.INTERNATIONAL_ITINERARIES)?window.INTERNATIONAL_ITINERARIES:[],selected=new Set(planCartRead().map(x=>x.id));const m=plans.filter(p=>[p.destination,p.country,p.style,p.duration,...(p.highlights||[])].join(" ").toLowerCase().includes(q));box.innerHTML=m.length?m.map(p=>{const i=itineraryToCartItem(p),a=selected.has(i.id);return`<button type="button" class="plan-destination-result ${a?"is-added":""}" data-pick-plan="${planCartEscape(p.id)}"><span class="plan-destination-result-icon">🗺️</span><span class="plan-destination-result-text"><strong>${planCartEscape(p.destination)} — ${planCartEscape(p.style)}</strong><small>${planCartEscape(p.duration)} · ${planCartEscape((p.highlights||[]).slice(0,3).join(" · "))}</small></span><span class="plan-destination-result-action">${a?"✓ Added":"+ Add"}</span></button>`}).join(""):"<div class=\"plan-destination-no-results\">No tour plan found.</div>";box.querySelectorAll("[data-pick-plan]").forEach(b=>b.addEventListener("click",()=>{const p=plans.find(x=>x.id===b.dataset.pickPlan);if(p)planCartAdd(itineraryToCartItem(p));renderPlanCart();renderPlanResults()}))}
function switchPlanTab(tab){document.querySelectorAll(".plan-cart-tab").forEach(b=>b.classList.toggle("is-active",b.dataset.planTab===tab));const d=document.getElementById("plan-cart-destination-picker"),p=document.getElementById("plan-cart-plan-picker");if(d)d.hidden=tab!=="destinations";if(p)p.hidden=tab!=="plans";if(tab==="plans")renderPlanResults();else renderDestinationResults()}
function ensureCardButtonStyles(){if(document.getElementById("nature-plan-card-button-style"))return;const s=document.createElement("style");s.id="nature-plan-card-button-style";s.textContent=`.nature-plan-card-action{margin-top:12px;width:100%;border:0;border-radius:9px;padding:9px 12px;background:#168bd3;color:#fff;font-weight:800;font-size:12px;cursor:pointer}.nature-plan-card-action.is-added{background:#0f9d58}.nature-current-destination-action{margin:18px 0 6px!important;display:inline-flex!important;width:auto!important}`;document.head.appendChild(s)}
function cardPlanData(card){const h=card.querySelector("h3,h4,h2"),img=card.querySelector("img");if(!h||!img)return null;const n=h.textContent.trim();if(!n||/nature tours|wild safaris|honeymoon packages|medical tourism|sample international itineraries/i.test(n))return null;const found=planDestinationCatalogue.find(d=>d.name&&n.toLowerCase().includes(String(d.name).toLowerCase()));return found?destinationToCartItem(found):{id:`card-${location.pathname}-${n.toLowerCase().replace(/[^a-z0-9]+/g,"-")}`,type:"destination",destination:n,country:"",duration:"Custom plan",style:"Custom itinerary"}}
function addPlanButtonToCard(card){if(card.querySelector(".nature-plan-card-action")||card.querySelector(".itinerary-secondary"))return;const item=cardPlanData(card);if(!item)return;const b=document.createElement("button");b.type="button";b.className="nature-plan-card-action";const sync=()=>{const a=planCartRead().some(x=>x.id===item.id);b.textContent=a?"✓ Added to Plan":"🧳 Add to Plan";b.classList.toggle("is-added",a)};sync();b.addEventListener("click",()=>{planCartAdd(item);sync();openPlanCart()});(card.querySelector(".card-meta")||card).appendChild(b)}
function enhancePlanCards(){ensureCardButtonStyles();document.querySelectorAll(".glance-card,.destination-card,.search-result-card,.result-card").forEach(addPlanButtonToCard)}
async function addCurrentDestinationButton(){const host=document.getElementById("destination-page");if(!host)return;const run=async()=>{if(host.querySelector(".nature-current-destination-action"))return;let d=null;try{const id=new URLSearchParams(location.search).get("id")||localStorage.getItem("natureToursDestination");if(window.DestinationEngine){const all=await window.DestinationEngine.load();d=all.find(x=>String(x.id)===String(id))}if(!d)d=JSON.parse(localStorage.getItem("natureToursDynamicDestination")||"null")}catch(_){}if(!d)return;const i=destinationToCartItem(d),b=document.createElement("button");b.type="button";b.className="nature-plan-card-action nature-current-destination-action";const sync=()=>{const a=planCartRead().some(x=>x.id===i.id);b.textContent=a?"✓ Added to My Plan":"🧳 Add to My Plan";b.classList.toggle("is-added",a)};sync();b.onclick=()=>{planCartAdd(i);sync();openPlanCart()};const h=host.querySelector("h1,h2,h3");(h?.parentElement||host).appendChild(b)};run();let tries=0;const timer=setInterval(()=>{tries++;run();if(tries>40)clearInterval(timer)},250)}

function travellerSummary(form){const a=form.querySelector("#traveller-adults-enabled")?.checked?Number(form.querySelector("#traveller-adults")?.value||0):0,k=form.querySelector("#traveller-kids-enabled")?.checked?Number(form.querySelector("#traveller-kids")?.value||0):0,b=form.querySelector("#traveller-babies-enabled")?.checked?Number(form.querySelector("#traveller-babies")?.value||0):0,s=form.querySelector("#traveller-seniors-enabled")?.checked?Number(form.querySelector("#traveller-seniors")?.value||0):0,sp=form.querySelector("#traveller-special-enabled")?.checked?(form.querySelector("#traveller-special-description")?.value.trim()||"Description not provided"):"";const parts=[];if(a)parts.push(`Adults: ${a}`);if(k)parts.push(`Kids (age 4 to 18): ${k}`);if(b)parts.push(`Babies (age 0 to 4): ${b}`);if(s)parts.push(`Senior citizens (60 and above): ${s}`);if(sp)parts.push(`Special passenger: ${sp}`);return{total:a+k+b+s,summary:parts.length?parts.join(" | "):"No traveller type selected"}}
function setupTravellerControls(form){const pairs=["adults","kids","babies","seniors","special"].map(type=>{const check=form.querySelector(`#traveller-${type}-enabled`),input=form.querySelector(`#traveller-${type}`),desc=type==="special"?form.querySelector("#traveller-special-description"):null;return{check,input,desc}});const refresh=()=>{pairs.forEach(({check,input,desc})=>{const on=!!check?.checked;if(input)input.disabled=!on;if(desc)desc.disabled=!on});const s=travellerSummary(form);const total=form.querySelector("#traveller-total");if(total)total.textContent=`Total travellers selected: ${s.total}`};pairs.forEach(({check})=>check?.addEventListener("change",refresh));refresh()}
function buildWhatsAppLink(items,form){const travellers=travellerSummary(form);const list=items.map(i=>`• ${i.type==="itinerary"?"Tour plan: ":"Destination: "}${i.destination}${i.country?`, ${i.country}`:""} — ${i.duration||"Custom plan"} (${i.style||"Custom itinerary"})`).join("%0A");const dates=encodeURIComponent(form?.travelDates?.value?.trim()||"Not specified"),budget=encodeURIComponent(form?.budget?.value?.trim()||"Not specified"),notes=encodeURIComponent(form?.notes?.value?.trim()||"None"),trav=encodeURIComponent(travellers.summary);return`https://wa.me/${PLAN_CART_WHATSAPP}?text=Hello%20Nature%20Tours,%0A%0AI%20would%20like%20to%20discuss%20these%20travel%20plans:%0A%0A${list}%0A%0ATravellers:%20${trav}%0ATotal%20travellers:%20${travellers.total}%0ATravel%20dates:%20${dates}%0ABudget:%20${budget}%0AOther%20special%20requirements:%20${notes}%0A%0APlease%20contact%20me%20with%20a%20customised%20plan%20and%20quotation.%0A%0AThank%20you.`}
function openPlanCart(){const p=document.getElementById("plan-cart-panel");if(!p)return;p.classList.add("is-open");p.setAttribute("aria-hidden","false");renderPlanCart();renderDestinationResults();renderPlanResults();setTimeout(()=>document.getElementById("plan-destination-search")?.focus(),120)}
function closePlanCart(){const p=document.getElementById("plan-cart-panel");if(!p)return;p.classList.remove("is-open");p.setAttribute("aria-hidden","true")}

async function initializePlanCart(){ensurePlanCartStyles();ensurePlanCartMarkup();ensureCardButtonStyles();planDestinationCatalogue=await loadPlanDestinations();await ensureItineraryCatalogue();enhancePlanCards();addCurrentDestinationButton();const ob=document.getElementById("open-plan-cart"),cb=document.getElementById("close-plan-cart"),bd=document.getElementById("plan-cart-backdrop"),form=document.getElementById("plan-cart-enquiry-form");if(ob&&!ob.dataset.bound){ob.onclick=openPlanCart;ob.dataset.bound="true"}if(cb&&!cb.dataset.bound){cb.onclick=closePlanCart;cb.dataset.bound="true"}if(bd&&!bd.dataset.bound){bd.onclick=closePlanCart;bd.dataset.bound="true"}document.querySelectorAll("[data-plan-tab]").forEach(b=>{b.onclick=()=>switchPlanTab(b.dataset.planTab)});const ds=document.getElementById("plan-destination-search"),ps=document.getElementById("plan-plan-search");ds?.addEventListener("input",renderDestinationResults);ps?.addEventListener("input",renderPlanResults);if(form){setupTravellerControls(form);form.addEventListener("submit",e=>{e.preventDefault();const items=planCartRead();if(!items.length){alert("Please add at least one destination or tour plan first.");return}const t=travellerSummary(form);if(!t.total){alert("Please select at least one traveller type and enter the number of travellers.");return}window.open(buildWhatsAppLink(items,form),"_blank","noopener,noreferrer")})}document.addEventListener("natureToursPlanCartUpdated",()=>{updatePlanCartButtons();renderPlanCart();renderDestinationResults();renderPlanResults();enhancePlanCards()});document.addEventListener("keydown",e=>{if(e.key==="Escape")closePlanCart()});window.addEventListener("storage",e=>{if(e.key===PLAN_CART_KEY){updatePlanCartButtons();renderPlanCart()}});const observer=new MutationObserver(()=>{enhancePlanCards();addCurrentDestinationButton()});observer.observe(document.body,{childList:true,subtree:true});updatePlanCartButtons();renderPlanCart();renderDestinationResults()}
window.NatureToursPlanCart={read:planCartRead,write:planCartWrite,add:planCartAdd,count:planCartCount,open:openPlanCart,close:closePlanCart,render:renderPlanCart};
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",initializePlanCart,{once:true});else initializePlanCart();