/* Nature Tours — universal live hotel + itinerary layer + Plan Cart + enquiry */
(function(){'use strict';
const WA='919822339466',cache=new Map(),usedImages=new Set();
const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\"/g,'&quot;').replace(/'/g,'&#039;');
async function json(u,o){const r=await fetch(u,o);if(!r.ok)throw new Error('HTTP '+r.status);return r.json()}
async function geocode(d){const k='geo:'+d.id;if(cache.has(k))return cache.get(k);const queries=[`${d.name}, ${d.region||''}, ${d.country||'India'}`,`${d.name}, ${d.country||'India'}`];for(const q0 of queries){const q=encodeURIComponent(q0.replace(/,\s*,/g,','));try{const a=await json('https://nominatim.openstreetmap.org/search?format=jsonv2&limit=5&q='+q,{headers:{Accept:'application/json'}});if(a?.length){const best=a.find(x=>x.type==='city'||x.type==='town'||x.type==='village'||x.type==='municipality'||x.type==='administrative')||a[0],p={lat:+best.lat,lon:+best.lon};cache.set(k,p);return p}}catch(_){} }cache.set(k,null);return null}
function tourismQuery(lat,lon,radius){return `[out:json][timeout:45];(nwr["tourism"~"^(hotel|resort|guest_house|hostel|motel|camp_site|alpine_hut|chalet)$"](around:${radius},${lat},${lon});nwr["building"="hotel"](around:${radius},${lat},${lon}););out center tags;`}
function normaliseHotels(elements,d){const result=[],seen=new Set();for(const i of elements||[]){const t=i.tags||{},name=String(t.name||'').trim(),nk=name.toLowerCase().replace(/\s+/g,' '),lat=i.lat??i.center?.lat,lon=i.lon??i.center?.lon;if(!name||seen.has(nk)||!Number.isFinite(Number(lat))||!Number.isFinite(Number(lon)))continue;seen.add(nk);result.push({id:`osm-${i.type}-${i.id}`,name,lat:+lat,lon:+lon,address:[t['addr:housenumber'],t['addr:street'],t['addr:place'],t['addr:city']||t['addr:town']||t['addr:village']||d.name].filter(Boolean).join(', '),stars:t.stars||t['hotel:stars']||'',website:t.website||t['contact:website']||'',phone:t.phone||t['contact:phone']||'',type:t.tourism||'hotel'})}return result}
async function hotelsFromOSM(d){const k='hotels:'+d.id;if(cache.has(k))return cache.get(k);const p=await geocode(d);if(!p)return[];const radii=[20000,50000,80000];let best=[];try{for(const radius of radii){const data=await json('https://overpass-api.de/api/interpreter',{method:'POST',headers:{'Content-Type':'text/plain;charset=UTF-8'},body:tourismQuery(p.lat,p.lon,radius)});const found=normaliseHotels(data.elements,d);if(found.length>best.length)best=found;if(best.length>=6)break}const out=best.slice(0,12);cache.set(k,out);return out}catch(_){cache.set(k,[]);return[]}}
async function commonsPhoto(h,d){for(const term of [`${h.name} ${d.name}`,h.name,`${h.name} ${d.region||''}`])try{const u='https://commons.wikimedia.org/w/api.php?action=query&generator=search&gsrsearch='+encodeURIComponent(term)+'&gsrnamespace=6&gsrlimit=12&prop=imageinfo&iiprop=url&iiurlwidth=900&format=json&origin=*',data=await json(u);for(const p of Object.values(data.query?.pages||{})){if(!/hotel|resort|lodge|inn|hostel|guest.?house|camp|chalet|villa|palace/.test(String(p.title||'').toLowerCase()))continue;const s=p.imageinfo?.[0]?.thumburl||p.imageinfo?.[0]?.url||'';if(s&&!usedImages.has(s)){usedImages.add(s);return s}}}catch(_){}return''}
async function enrichHotels(d,hs){usedImages.clear();const out=[];for(const h of hs)out.push({...h,image:await commonsPhoto(h,d)});return out}
function highlights(d){const t=Array.isArray(d.tags)?d.tags.filter(Boolean):[];return[...new Set([...t,'Local sightseeing','Scenic viewpoints','Local cuisine','Cultural experience','Leisure time'])].slice(0,8)}
function makePlans(d){const h=highlights(d),specs=[[2,1,'Quick Escape'],[3,2,'Short Discovery'],[5,4,'Complete Experience'],[7,6,'Relaxed Explorer']];return specs.map(([days,nights,style])=>({id:`${d.id}-${days}d`,days,nights,style,name:d.name,duration:`${days} Days / ${nights} Nights`,schedule:Array.from({length:days},(_,i)=>{const day=i+1;if(day===1)return{day,morning:'Arrival and local orientation',afternoon:`Check in and explore ${h[0]}`,evening:`Relax and experience ${h[1]||'local highlights'}`};if(day===days)return{day,morning:`Breakfast and ${h[(i+1)%h.length]}`,afternoon:'Leisure, shopping or local experience',evening:'Departure'};return{day,morning:`Explore ${h[i%h.length]}`,afternoon:`Sightseeing: ${h[(i+1)%h.length]}`,evening:`Local experience: ${h[(i+2)%h.length]}`}})}))}
function readCart(){try{return JSON.parse(localStorage.getItem('natureToursPlanCart')||'[]')}catch(_){return[]}}
function saveCart(items){localStorage.setItem('natureToursPlanCart',JSON.stringify(items));document.dispatchEvent(new CustomEvent('natureToursPlanCartUpdated'));renderCart()}
function addCart(item){const items=readCart();if(items.some(x=>x.id===item.id))return false;items.push(item);saveCart(items);return true}
function removeCart(id){saveCart(readCart().filter(x=>x.id!==id))}
function enquiry(){if(!readCart().length){alert('Your Plan Cart is empty.');return}location.href='enquiry.html'}
function cartUI(){if(document.getElementById('nt-cart'))return;const style=document.createElement('style');style.textContent='.nt-cart-btn{position:fixed;right:20px;bottom:20px;z-index:9999;border:0;border-radius:999px;padding:13px 18px;background:#111;color:#fff;font-weight:700;cursor:pointer;box-shadow:0 8px 28px #0003}.nt-cart-panel{position:fixed;right:20px;bottom:76px;width:min(390px,calc(100vw - 40px));max-height:70vh;overflow:auto;background:#fff;color:#111;z-index:10000;border-radius:18px;box-shadow:0 15px 50px #0003;padding:18px;display:none}.nt-cart-panel.open{display:block}.nt-cart-item{border-bottom:1px solid #ddd;padding:12px 0}.nt-cart-item img{width:70px;height:55px;object-fit:cover;border-radius:8px;float:left;margin-right:10px}.nt-cart-remove{float:right;border:0;background:none;cursor:pointer}.nt-cart-actions{display:flex;gap:8px;margin-top:14px}.nt-cart-actions button{flex:1;padding:11px;border:0;border-radius:10px;cursor:pointer}.nt-cart-enquire{background:#111;color:#fff}.nt-cart-clear{background:#eee}.nt-cart-empty{padding:20px 0;color:#666}';document.head.appendChild(style);const b=document.createElement('button');b.id='nt-cart';b.className='nt-cart-btn';b.type='button';b.textContent='🛒 Plan Cart (0)';const p=document.createElement('aside');p.className='nt-cart-panel';p.innerHTML='<h2>Your Plan Cart</h2><div class="nt-cart-list"></div><div class="nt-cart-actions"><button class="nt-cart-clear">Clear Cart</button><button class="nt-cart-enquire">Proceed to Enquiry</button></div>';document.body.append(b,p);b.onclick=()=>{p.classList.toggle('open');renderCart()};p.querySelector('.nt-cart-clear').onclick=()=>{if(confirm('Clear your Plan Cart?'))saveCart([])};p.querySelector('.nt-cart-enquire').onclick=enquiry;renderCart()}
function renderCart(){const b=document.getElementById('nt-cart'),p=document.querySelector('.nt-cart-panel');if(!b||!p)return;const items=readCart();b.textContent=`🛒 Plan Cart (${items.length})`;const list=p.querySelector('.nt-cart-list');if(!items.length){list.innerHTML='<div class="nt-cart-empty">Your cart is empty.<br>Add a hotel or itinerary to start planning.</div>';return}list.innerHTML=items.map(x=>`<div class="nt-cart-item">${x.image?`<img src="${esc(x.image)}" alt="">`:''}<button class="nt-cart-remove" data-id="${esc(x.id)}">✕</button><strong>${esc(x.destination||'Trip')}</strong><br><small>${x.type==='itinerary'?esc(x.duration||'Itinerary'):'🏨 '+esc(x.hotel||'Hotel')}</small>${x.type==='itinerary'&&x.hotel?`<br><small>Hotel: ${esc(x.hotel.name||x.hotel)}</small>`:''}<div style="clear:both"></div></div>`).join('');list.querySelectorAll('.nt-cart-remove').forEach(x=>x.onclick=()=>removeCart(x.dataset.id))}
function hotelCard(h,d){const photo=h.image?`<img class="live-hotel-photo" src="${esc(h.image)}" alt="${esc(h.name)}" loading="lazy">`:'<div class="live-hotel-no-photo"><strong>Photo unavailable</strong><span>No verified hotel photograph found</span></div>';const map='https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(h.name+' '+(h.address||d.name)),c=document.createElement('article');c.className='live-hotel-card';c.innerHTML=`${photo}<div class="live-hotel-body"><div class="live-hotel-source">✓ Real listing · OpenStreetMap</div><h3>${esc(h.name)}</h3>${h.stars?`<p>⭐ ${esc(h.stars)} star</p>`:''}<p class="live-hotel-address">${esc(h.address||d.name)}</p><div class="live-hotel-actions"><a href="${esc(map)}" target="_blank" rel="noopener">Maps</a>${h.website?`<a href="${esc(h.website)}" target="_blank" rel="noopener">Website</a>`:''}<button type="button">+ Add hotel</button></div></div>`;c.querySelector('button').onclick=()=>{const ok=addCart({id:`hotel-${h.id}`,sourceId:h.id,type:'hotel',destination:d.name,country:d.country||'India',hotel:h.name,address:h.address||'',image:h.image||'',website:h.website||''});c.querySelector('button').textContent=ok?'✓ Added':'✓ Already Added';c.querySelector('button').disabled=true};return c}
function renderHotels(d,hs){const page=document.getElementById('destination-page');if(!page)return;page.querySelector('.live-hotels')?.remove();const s=document.createElement('section');s.className='live-hotels';s.innerHTML=`<div class="planner-heading"><span>🏨 Stay</span><h2>Real Hotels & Stays in ${esc(d.name)}</h2><p>Live verified accommodation listings from OpenStreetMap. We include hotels, resorts, guesthouses, hostels and camps where available.</p></div><div class="live-hotel-grid"></div>`;const g=s.querySelector('.live-hotel-grid');hs.forEach(h=>g.appendChild(hotelCard(h,d)));if(!hs.length)g.innerHTML='<div class="planner-empty">No verified accommodation listings were returned for this destination right now.</div>';page.appendChild(s)}
function renderPlans(d,hs){const page=document.getElementById('destination-page');if(!page)return;page.querySelector('.live-itineraries')?.remove();const s=document.createElement('section');s.className='live-itineraries';s.innerHTML=`<div class="planner-heading"><span>🗓️ Plan your trip</span><h2>Itineraries for ${esc(d.name)}</h2><p>Choose a duration and connect a verified hotel to your plan.</p></div><div class="live-itinerary-grid"></div>`;const g=s.querySelector('.live-itinerary-grid');makePlans(d).forEach(plan=>{const c=document.createElement('article');c.className='live-itinerary-card';const opts=hs.map((h,i)=>`<option value="${i}">${esc(h.name)}</option>`).join('');c.innerHTML=`<div class="live-plan-badge">${esc(plan.style)}</div><h3>${esc(plan.duration)}</h3><label>Hotel for this plan<select>${opts||'<option value="">Hotel selection unavailable</option>'}</select></label><div class="live-schedule">${plan.schedule.map(day=>`<div class="live-day"><strong>Day ${day.day}</strong><p><b>Morning:</b> ${esc(day.morning)}</p><p><b>Afternoon:</b> ${esc(day.afternoon)}</p><p><b>Evening:</b> ${esc(day.evening)}</p></div>`).join('')}</div><button class="live-plan-add" type="button">+ Add itinerary to Plan Cart</button>`;c.querySelector('button').onclick=()=>{const h=hs[Number(c.querySelector('select').value)]||null;const ok=addCart({id:`itinerary-${plan.id}`,sourceId:plan.id,type:'itinerary',destination:plan.name,country:d.country||'India',duration:plan.duration,style:plan.style,schedule:plan.schedule,hotel:h?{id:h.id,name:h.name,image:h.image||'',address:h.address||''}:null});c.querySelector('button').textContent=ok?'✓ Added to Plan Cart':'✓ Already Added'};g.appendChild(c)});page.appendChild(s)}
async function init(){const page=document.getElementById('destination-page');if(!page||!window.DestinationEngine)return;cartUI();try{const p=new URLSearchParams(location.search),requested=p.get('id')||p.get('destination')||'',d=await window.DestinationEngine.find(requested);if(!d)return;const hs=await hotelsFromOSM(d),enriched=await enrichHotels(d,hs);renderHotels(d,enriched);renderPlans(d,enriched)}catch(e){console.warn('Live travel planner failed',e)}}
document.addEventListener('DOMContentLoaded',()=>setTimeout(init,1300));document.addEventListener('natureToursPlanCartUpdated',renderCart);
})();
